fail_fast: true
repos:
  - repo: local
    hooks:
      - id: check-manifest
        name: check-manifest
        entry: check-manifest
        language: system
        pass_filenames: false
        files: ^MANIFEST\.in$

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        args: [--filter-files]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
